name: template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: 5.3.0
  flutter_flavorizr: ^2.2.1
  injectable_generator: ^2.4.1

  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

# region: flutter pub run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# flavor region: flutter pub run flutter_flavorizr
flavorizr:
  flavors:
    prod:
      app:
        name: "Template"
      android:
        applicationId: "com.template.demo"
      ios:
        bundleId: "com.template.demo"
    dev:
      app:
        name: "Template Dev"
      android:
        applicationId: "dev.template.demo"
      ios:
        bundleId: "dev.template.demo"
