name: Analyze Dart code

on:
  pull_request:
    branches: ["dev", "main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.6"
      - name: Install dependencies
        run: |
          flutter pub get
      - name: Analyze project source
        run: |
          flutter analyze
